from calculadora import soma

resultado = soma(5, 3)
print(f"A soma é: {resultado}")
print(soma('15', 5))  # Isso deve gerar um erro de asserção